export const Events = {
  UPDATE_USER: "UPDATE_USER",
  SET_USER_NAME: "SET_USER_NAME",
  NEW_GAME: "NEW_GAME",
  JOIN_GAME: "JOIN_GAME",
  LEAVE_GAME: "LEAVE_GAME",
  UPDATE_GAME: "UPDATE_GAME",
  MOVE: "MOVE",
  UPDATE_POSITION: "UPDATE_POSITION"
};
