export const Events = {
  UPDATE_USER: "UPDATE_USER",
  SET_USER_NAME: "SET_USER_NAME",
  SET_USER_READY: "SET_USER_READY",
  NEW_GAME: "NEW_GAME",
  JOIN_GAME: "JOIN_GAME",
  CANNOT_JOIN: "CANNOT_JOIN",
  LEAVE_GAME: "LEAVE_GAME",
  UPDATE_GAME: "UPDATE_GAME",
  START_GAME: "START_GAME",
  MOVE: "MOVE",
  UPDATE_POSITION: "UPDATE_POSITION",
  UPDATE_MOB: "UPDATE_MOB",
};
